module.exports = {
  'modules/**/*.{js,ts,json,d.ts}': files => {
    // worker-configuration.d.ts is generated by wrangler and listed in .eslintignore;
    // passing an ignored file to eslint explicitly yields a warning that fails --max-warnings 0.
    const kept = files.filter(f => !f.endsWith('worker-configuration.d.ts'))
    return kept.length ? [`eslint --max-warnings 0 --fix ${kept.join(' ')}`] : []
  },
  'package.json': ['yarn sort-package-json'],
  'modules/**/package.json': ['yarn sort-package-json'],
}
