#!/bin/bash

set -e

yarn test

REPORT_FILE=$(mktemp)
npx monocrate@0.17.0 publish modules/septima-lang --bump=patch --report=$REPORT_FILE

NEXT_VERSION=$(node -p "fs.readFileSync(\"$REPORT_FILE\").toString().trim()")

T="published@$NEXT_VERSION"
echo tagging "$T"
git tag "$T"
git push --tags
