#!/bin/bash

set -e

yarn test
pushd modules/septima-lang
CURRENT_VERSION=$(npm info septima-lang version)
npm pkg set "version=$CURRENT_VERSION"
npm version minor
NEXT_VERSION=$(npm pkg get version | tr -d '"')
echo "resolved new version: $NEXT_VERSION"
npm publish
popd


T="published@$NEXT_VERSION"
echo tagging "$T"
git tag "$T"
git push --tags
